### ISSUE TITLE
Timeout Error :(

### ISSUE THREAD

**Issue by sawankumar** [jagrit007/Telegram-CloneBot#1]
_Tried Coping 8TB and it throws Timeout Error._

**Logs :-**

2020-07-29T12:39:14.692732+00:00 app[worker.1]: An uncaught error was raised while running the promise
2020-07-29T12:39:14.692742+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-29T12:39:14.692742+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/promise.py", line 56, in run
2020-07-29T12:39:14.692743+00:00 app[worker.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2020-07-29T12:39:14.692743+00:00 app[worker.1]:   File "clonerbot.py", line 158, in clone
2020-07-29T12:39:14.692744+00:00 app[worker.1]:     message.edit_text(to_send)
2020-07-29T12:39:14.692744+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/message.py", line 876, in edit_text
2020-07-29T12:39:14.692745+00:00 app[worker.1]:     chat_id=self.chat_id, message_id=self.message_id, *args, **kwargs)
2020-07-29T12:39:14.692745+00:00 app[worker.1]:   File "<decorator-gen-27>", line 2, in edit_message_text
2020-07-29T12:39:14.692745+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
2020-07-29T12:39:14.692746+00:00 app[worker.1]:     result = func(*args, **kwargs)
2020-07-29T12:39:14.692746+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 1898, in edit_message_text
2020-07-29T12:39:14.692746+00:00 app[worker.1]:     return self._message(url, data, timeout=timeout, reply_markup=reply_markup, **kwargs)
2020-07-29T12:39:14.692747+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 175, in _message
2020-07-29T12:39:14.692747+00:00 app[worker.1]:     result = self._request.post(url, data, timeout=timeout)
2020-07-29T12:39:14.692747+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
2020-07-29T12:39:14.692747+00:00 app[worker.1]:     **urlopen_kwargs)
2020-07-29T12:39:14.692748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 237, in _request_wrapper
2020-07-29T12:39:14.692748+00:00 app[worker.1]:     message = self._parse(resp.data)
2020-07-29T12:39:14.692748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 195, in _parse
2020-07-29T12:39:14.692756+00:00 app[worker.1]:     raise RetryAfter(retry_after)
2020-07-29T12:39:14.692756+00:00 app[worker.1]: telegram.error.RetryAfter: Flood control exceeded. Retry in 9 seconds

**Comment by jagrit007** [comment]
It just logs that exception as an Error but everything should go fine after some seconds. Anyway, if you face it often or if you do multiple clones, change the message update interval to something higher.
 
**Telegram API Limits** :
- Private Chat Limit - 60 edits (or requests) per minute

- Group Chat limit - 30 edits (or requests) per minute.

**Comment by sawankumar** [comment]
@jagrit007 Also can I use this to clone TeamDrive or just folder ?

**Comment by jagrit007** [comment]
> @jagrit007 Also can I use this to clone TeamDrive or just folder ?

You need to have at least viewing rights in that TeamDrive.

- If you're using SAs, your SAs/Google Group must be in the TD

- If not using Service Accounts, your primary account should be in the TD but you will only be able to copy 750GB every 24 hours.

**Comment by OryWareKyrie** [comment]
> It just logs that exception as an Error but everything should go fine after some seconds. Anyway, if you face it often or if you do multiple clones, change the message update interval to something higher.

I'm sorry to ask but where do I change this update interval?
