### ISSUE TITLE
Heroku ERROR

### ISSUE THREAD

**Issue by blinditachi** [jagrit007/Telegram-CloneBot#18]
this is my heroku logs:

2021-04-27T18:27:17.132784+00:00 app[worker.1]: 2021-04-27 18:27:17,131 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
2021-04-27T18:27:17.132798+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-27T18:27:17.132809+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/utils/promise.py", line 57, in run
2021-04-27T18:27:17.132811+00:00 app[worker.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2021-04-27T18:27:17.132811+00:00 app[worker.1]:   File "/app/bot/decorators.py", line 7, in wrapper
2021-04-27T18:27:17.132812+00:00 app[worker.1]:     if args[0].effective_message.from_user.id in AUTHORISED_USERS or args[0].message.chat_id in AUTHORISED_USERS:
2021-04-27T18:27:17.132812+00:00 app[worker.1]: TypeError: argument of type 'int' is not iterable

**Comment by Agamya-Samuel** [comment]
nothig clear, send full logs, but I suspect, it has something to do with your AUTHORISED_USERS, also send the format you used in AUTHORISED_USERS
