### ISSUE TITLE
when cloning any file by using the bot i created  it shows that "FileNotFoundError: [Errno 2] No such file or directory: 'accounts/0.json''

### ISSUE THREAD

**Issue by AmirulAndalib** [jagrit007/Telegram-CloneBot#7]
when cloning any file by using the bot i created  it shows that "FileNotFoundError: [Errno 2] No such file or directory: 'accounts/0.json''

please help

here is the command i used :-

/clone https://drive.google.com/drive/u/1/folders/1WSQ8AJLdqhYJxOSFLcMVh1dEckens2hG-1WSQ8AJLdqhYJxOSFLcMVh1dEckens2hG

the dash  before -1ws is the folder i want to clone and the 1WSxxxxxxxx it the  destination folder  i made the bot with repl.run as of your video please hellp

here are my complete heroku logs:-https://pastebin.com/grYMFPqF

my telegram id:- https://t.me/L3G10Nx                         /  @L3G10Nx

i followed all of your instructions as shown on your video

please help me fix this

**Comment by jagrit007** [comment]
Your service account folder: "accounts" is missing. 

Repl.it does not download that folder for some reason.

So move it to **bot** folder, download zip, extract zip, move back the **accounts** folder out of the **bot** folder. Upload to GitHub by dragging files on the upload page and finally attach that to **Heroku**

Try this and it should fix the problem.

And to select a destination for clone just use whitespace instead of **Hyphen** **-**
eg. `/clone https://drive.google.com/drive/u/1/folders/1WSQ8AJLdqhYJxOSFLcMVh1dEckens2hG 1WSQ8AJLdqhYJxOSFLcMVh1dEckens2hG`

**Comment by AmirulAndalib** [comment]
which one gen_sa_accounts.py         /   credentials.json?

**Comment by AmirulAndalib** [comment]
yup bro i took that into account but a new error emerged
when i type the command ''python3 -m bot'' the error shows shows up called ''no module named ''telegram''
and some more other things.......

(python3 -m bot
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/runner/Telegram-CloneBot-9/bot/__init__.py", line 4, in <module>
    import telegram.ext as tg
ModuleNotFoundError: No module named 'telegram')



how to fix this? i putted bot token and everything correctly there

**Comment by AmirulAndalib** [comment]
yup bro i took that into Account but new error emerged 

2020-11-20T13:43:32.193494+00:00 app[worker.1]:     return func(*args, **kwargs)
2020-11-20T13:43:32.193494+00:00 app[worker.1]:   File "/app/bot/__main__.py", line 54, in cloneNode
2020-11-20T13:43:32.193494+00:00 app[worker.1]:     gd = GoogleDriveHelper(GFolder_ID=DESTINATION_ID)
2020-11-20T13:43:32.193495+00:00 app[worker.1]:   File "/app/bot/gDrive.py", line 44, in __init__
2020-11-20T13:43:32.193495+00:00 app[worker.1]:     self.__service = self.authorize()
2020-11-20T13:43:32.193496+00:00 app[worker.1]:   File "/app/bot/gDrive.py", line 277, in authorize
2020-11-20T13:43:32.193496+00:00 app[worker.1]:     credentials = flow.run_console(port=0)
2020-11-20T13:43:32.193496+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 412, in run_console
2020-11-20T13:43:32.193497+00:00 app[worker.1]:     code = input(authorization_code_message)
2020-11-20T13:43:32.196744+00:00 app[worker.1]: EOFError: EOF when reading a line




i didnt use service Account because i cant add them to drive folder for some reason but downloaded and added them to my git repo

😓

**Comment by AmirulAndalib** [comment]
ok thanks but another issue

**Comment by abhishek-sharma8** [comment]
I have the same issue. SAs are added to the team drive. Can you please help?
